### PR TITLE
Added sphinx documentation

### LINKED ISSUE #45: Documentation pages (sphinx/readthedocs)
- [ ] Home/intro (@mooniean)
- [ ] Installation (move from README) (@JatGreer)
- [ ] Notebooks/tutorials (link to these?) (@mooniean)
- [x] API reference (autogenerated from docstrings) (@ots22 - on #46 - just generating these, still need to write many docstrings per #18)
- [ ] Contributing guide

(please add to this list)

### PR DESCRIPTION
**Pull request by mooniean**
Added documentation for:
Installation (from README)
Contributing Guide
Index

Resolves #45 

@JatGreer feel free to add/remove what you think should be added, removed!

### CODE REVIEW

**Comment by mooniean** [comment]
the docs look all wonky, I'll try to fix them up a little bit.

**Comment by JatGreer** [comment]
Figured out i needed to do `pip install .[doc]`
For some reason I get this error when I try to build docs locally:
```
$ sphinx-build -M html docs _docsbuild
Running Sphinx v4.3.2

Theme error:
no theme named 'pydata-sphinx-theme' found (missing theme.conf?)
```
despite having installed the package and checking the package uses dashes in pyproject.toml and uses underscores in conf.py (which is correct according to docs: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/install.html)

I might have a local version of sphinx which is too modern installed. So testing by pushing to github workflow instead.

Some links needed to be converted to rst format instead of md, but I don't remember making any other updates. There's still more we gotta add the the docs pages.

**Comment by mooniean** [comment]
@JatGreer why do you think the installation page doesn't get updated?

**Comment by JatGreer** [comment]
@mooniean  I think it is because `cd` has special meaning in rst: https://docutils.sourceforge.io/docs/ref/rst/directives.html#compound-paragraph. Github highlighted it within the rst file - otherwise I wouldn't have found it.
Escape char looks to be `\`. Hopefully this new commit should fix things for installation.rst

**Pull request merged**
